### PR TITLE
Delete subsctype.c

### PR DESCRIPTION
**Pull request by dfedorov-solace**
Removed unused file

---
This change is [Reviewable](https://reviewable.io/reviews/openmama/openmama/158)

### CODE REVIEW

**Comment by fquinner** [comment]
Yup - definition duplicates that of `subscriptiontype.c`.- we'll get this in.

For future reference, can you raise pull requests against next and use your own feature branch which has been split out off 'next', for these as per https://github.com/OpenMAMA/OpenMAMA/wiki/Submission-Process ? There's good reasons for it too we're not just being pedantic:

1. Next is the development HEAD so it prevents merge problems because that's where the change will utimately land.
2. Github uses the entirety of the source branch (in your case dfedorov-solace:master) to represent the change, so if you added any other change to your fork's 'master' branch, it would actually get *appended* to the pull request.

As I said though that's very a much "for next time" deal - this PR is grand for now because we'll cherry pick the change anyway.

**Comment by dfedorov-solace** [comment]
Thank you Frank, I'm not sure I understand the motivation for this "Next is the development HEAD" but I'll follow the process next time as you're asking.
Regards
Dmitri

**Comment by MattMulhern** [comment]
> Next is the development HEAD so it prevents merge problems because that's where the change will ultimately land

Just to clarify, I believe frank means that the 'next' branch is where all commits land initially and thus represents the most up-to-date version of the code. 

Basing your PR's off of this branch greatly decreases the chance of merge conflicts (master is only updated on each major release) which speeds up the process of getting your code into OpenMAMA.

**Comment by dfedorov-solace** [comment]
I see; thanks Matt.
You know guys, you could just tell me that you selected the so-called "Gitflow" workflow model, I wasn't born yesterday. I personally don't like that workflow (IMO it produces too many branches and too many merges), but any process is better than no process at all.
Thanks again.
Cheers
Dmitri

**Comment by fquinner** [comment]
Thanks Dmitri - now in next.

**Pull request closed without merging**
