### PR TITLE
CLANG Compilation issues

### PR DESCRIPTION
**Pull request by philippreston**
Couple of issues with clang compilation.

Unit Tests passing (-MamaPublisherTest* ala CI environment), Pub --> Sub and Capture Replay --> Mamalistenc - all ran with QPID 0.11.

[Review on Reviewable](https://reviewable.io/reviews/openmama/openmama/149)

### CODE REVIEW

**Comment by dmagOM** [comment]
Might be slightly pedantic, but it'd be good to get details of the compiler warnings that are being resolved in this case - I can tell the new line at EOF one, but I'm not sure about what the other is complaining about. Having the actual warning would probably help us make a more objective decision about the fix being correct.

D

**Comment by philippreston** [comment]
No problem.

New line:

```
mama/c_cpp/src/c/mama/entitlement.h:50:28: error: no newline at end of file [-Werror,-Wnewline-eof]
#endif /* EntitlementH__ */
```

Spaces:

```
mama/c_cpp/src/c/mamainternal.h:55:54: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define MAMA_PROP_BRIDGE_ENT_DEFERRED      "mama.%s."MAMA_PROP_BARE_ENT_DEFERRED
                                                     ^
```
 and 
                                                     
```
mama/c_cpp/src/c/mamainternal.h:56:54: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define MAMA_PROP_BRIDGE_COMPILE_TIME_VER  "mama.%s."MAMA_PROP_BARE_COMPILE_TIME_VER
```

**Comment by MattMulhern** [comment]
Seems grand, we'll get into the next rc / next.

**Comment by dmagOM** [comment]
Few more bits to come here which Phil and I are discussing, so can we hold off on merging just a little bit.

D

**Comment by MattMulhern** [comment]
OK, @dmagOM  I've assigned this to you, let us know when its good to go.

Thanks.

**Comment by dmagOM** [comment]
Cheers for the updates @philippreston, looks good to me. We'll get this merged to next.

D

**Comment by MattMulhern** [comment]
pushed to next (359485eff4ee71f821a18b47f0fb4af3f32f7f42..dece006966f6f7287cfd53df214b9279a7eb9269)

**Pull request closed without merging**
