### PR TITLE
Added Inno Setup installer script and LICENSE file

### PR DESCRIPTION
**Pull request by fquinner**
This change includes a configuration file for use with Inno Setup
which will convert an installation directory into an installer.

Also includes some intro and outro text to point the user
installing the software to places where they can find out more
information

Signed-off-by: Frank Quinn <fquinn.ni@gmail.com>

### CODE REVIEW

**Comment by fquinner** [comment]
Might be worth retro-creating OpenMAMA installers for the last release as the next one won't be expected until early 2017.

**Comment by dfedorov-solace** [comment]
Inno Setup? Why not a setup VS project?
No 3rd party dependency and exists for over 10 years.

**Comment by fquinner** [comment]
Because it's easy to understand and easy to use and that's the main thing i'm looking for here in the short term. Honestly if we move to cmake (like i am hoping we will), this would come for free with CPackWix so I'm inclined not to get too attached. If you would prefer to set up a visual studio project to do this though, I'll happily step back and let you contribute a VS project based installer if you have experience in such things?

**Comment by dfedorov-solace** [comment]
This is not a rocket science and I'll do it when I have a chance to.
My previous experience tells me that anything but native VS-project builds leads to supporting at least two sets of build specifications, and two is always too much :-): I wish I had a chance to influence that choice for this project, its too late now, but if you're considering WIX, please avoid it, it is good as a primitive replacement for setup projects when some dimwits at MS decided to remove it from VS, but now when it's back (I gather the dimwits moved to greener pastures from MS to Google LOL) there is really no intelligent reason to use WIX.

**Comment by fquinner** [comment]
But for APIs you *want* to support mutiple build specifications (64 and 32-bit). When using wix for Cmake you don't write any wix format output you just let it generate the output and you don't have any "installer" configuration to speak of. It also makes your installer generator part of your build infrastructure. I did try looking at native Wix and immediately hated life.

**Comment by dfedorov-solace** [comment]
Frank, sorry you'll never sell me CMake, especially under Windows :-).
I'm old school and if any software is from KDE4 for me it is just another reason not to use it.

**Comment by fquinner** [comment]
Merged the change so we have something today - if you contribute something superior, it'll replace this one.

**Pull request merged**
