### PR TITLE
Vector DateTime and Vector Price test cleanup

### PR DESCRIPTION
**Pull request by dfedorov-solace**
# Vector DateTime and Vector Price test cleanup
## Summary
Cleanup of vector datetime and vector price unit tests

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [X] Unit Tests
- [ ] Examples

## Details
Cleanup of vector datetime and vector price unit tests.

## Testing
Tested with the Qpid bridge

### CODE REVIEW

**Comment by fquinner** [comment]
Could you reinstate the removal of CHECK_NON_IMPLEMENTED_OPTIONAL please? They are so that these unit tests fail rather than core for payload bridges which don't implement this method. Otherwise it's grand.

**Comment by dfedorov-solace** [comment]
Well, I was under impression we don't have any payload bridges that don't implement it.
If I'm mistaken, I apologize and will revert it.

**Comment by fquinner** [comment]
Qpid is actually the only payload that does support this field type (unless you're adding to solace too) so yeah please revert.

**Comment by dfedorov-solace** [comment]
Yes, we've added it to the solace payload too.
Alright, reverting...

**Comment by dfedorov-solace** [comment]
will be redone with CHECK_NON_IMPLEMENTED_OPTIONAL back

**Comment by dfedorov-solace** [comment]
forget it, too much hassle :-)

**Pull request closed without merging**
