### PR TITLE
PLAT-493: Keeping track of CPP wrappers to default queue

### PR DESCRIPTION
**Pull request by MattMulhern**
## Areas Affected
*Place an 'x' within the braces to check the box*
- [ ] MAMAC
- [x] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
Currently, it is the responsibility of the middleware bridge to clean up it's default queue. In CPP, `Mama::getDefaultEventQueue` returns a CPP wrapper to this c-level queue. 

The wrapper is not tidied up and manually deleting could lead to a double free (mamaQueue::destroy tells the mw bridge to clean up the queue, which may be done again on bridge_close).

This patch keeps a track of any CPP wrappers made to default queues and cleans them up in Mama::close. This way the developer does not have to keep track of the default Queue wrapper created.

---
This change is [Reviewable](https://reviewable.io/reviews/openmama/openmama/174)

### CODE REVIEW

**Comment by fquinner** [comment]
Hi Matt,

This looks good, though could you rename defaultQueueWrappers to mDefaultQueueWrappers as it's a class member? Just noticed that this isn't actually detailed in the coding standards - we should add it.

Cheers,
Frank

**Comment by MattMulhern** [comment]
Dead on, that's renamed now and  i've updated the [C++ section](https://github.com/OpenMAMA/OpenMAMA/wiki/Coding-Standards#c-1) of the coding standards also.

**Comment by fquinner** [comment]
Can you resolve recently introduced conflicts please? Then its good to go.

**Comment by MattMulhern** [comment]
All conflicts resolved now.
I had to resolve come conflicts so I've intentionally left the merge commit in the branch.

**Pull request merged**
