### PR TITLE
[BZ-68] MAMA: Fix race conditions in mama queue/dispatcher + unit tes…

### PR DESCRIPTION
**Pull request by MattMulhern**
replacing [bz-68](http://bugs.openmama.org/show_bug.cgi?id=68)
original comments to follow.

[Review on Reviewable](https://reviewable.io/reviews/openmama/openmama/81)

### CODE REVIEW

**Comment by MattMulhern** [comment]
Damian Maguire 2014-03-11 17:31:58 UTC
Created attachment 42 [details]
Fix race conditions in MAMA queue dispatcher patch

Changed the mIsDispatching signalling variable into an atomic int since
its visible, inspected and modified across thread boundaries.  This is
the cause of several errors in helgrind and has been observed to cause
an issue with shutting down the queue within avis (may occur on other
middleware, but cannot reproduce with qpid).

Additional changes :-

- Fixed warning for uninitialised variables in msgutils.

- Rewrite of the MamaQueueTestC/MamaTimerTestC tests.  Fixed memory
  leaks, race conditions and off-by-one errors (causing some to execute
  across the boundary of indivisible tests).  Also added in allocation
  of transport to keep avis middleware happy (it doesn't construct a
  default transport so it didn't execute the tests properly).

All MamaQueueTestC/MamaTimerTestC tests now execute for both qpid and
avis (although the latter fails on some due to unimplemented features).

**Comment by MattMulhern** [comment]
Just a few initial comments on this patch:
> Index: mama/c_cpp/src/c/msgutils.c
> =============================================================
> --- mama/c_cpp/src/c/msgutils.c
> +++ mama/c_cpp/src/c/msgutils.c
> @@ -58,7 +58,7 @@
> ...

I think the msgutils.c changes look fine, but should probably be moved to their own patch, since they don't really relate to the rest of the changes in this file.


> Index: mama/c_cpp/src/c/queue.c
> =============================================================
> --- mama/c_cpp/src/c/queue.c
> +++ mama/c_cpp/src/c/queue.c
> ...
> @@ -226,7 +224,8 @@
> ...
> +    wInterlocked_initialize(&impl->mIsDispatching);
> +    wInterlocked_set(0, &impl->mIsDispatching);

Stylistic nitpick (I know, it's not really consistent) - on function calls, there should be a gap between the function name and the opening bracket of the parameter list. 

> @@ -587,6 +587,8 @@
>              {
>                  /* Dispatch messages for 10 ms. */
>                  ret = mamaQueue_timedDispatch(queue, 10);
> +
> +                /* Should this not react to MAMA_STATUS_TIMEOUT too? */
>                  if(MAMA_STATUS_OK == ret)
>                  {
>                      /* Add 10ms to the count. */

I agree with the comment, but with two caveats - firstly, comments aren't really the right place to have these kinds of discussions (so it should be removed, and a bugzilla ticket raised for it instead); secondly, I think there may be more issues with the implementation of this function than simply the function checking, but again that should be discussed in more detail on it's own ticket.

> @@ -785,32 +791,35 @@
>  mama_status
> mamaQueue_dispatch (mamaQueue queue)
> {
> -    mamaQueueImpl* impl = (mamaQueueImpl*)queue;
> +    mamaQueueImpl* impl   = (mamaQueueImpl*)queue;
> +    mama_status    status = MAMA_STATUS_OK;
> +

The status variable there is completely unused - it should be removed, meaning that part of the hunk can also be done away with. 

>  mama_status
>  mamaQueue_timedDispatch (mamaQueue queue,
>                           uint64_t  timeout)
>  {
> -    mamaQueueImpl* impl = (mamaQueueImpl*)queue;
> +   mamaQueueImpl* impl   = (mamaQueueImpl*)queue;

Slightly arbitrary formatting change, with no change to functionality, so that should also be removed.

> @@ -1261,16 +1270,10 @@
> {
>     mamaDispatcherImpl* impl = (mamaDispatcherImpl*)closure;
>  ...
> +    wInterlocked_set (1, &impl->mIsDispatching);
> +    while (wInterlocked_read (&impl->mIsDispatching) &&
> +           MAMA_STATUS_OK == mamaQueue_dispatch (impl->mQueue));
> +    wInterlocked_set (0, &impl->mIsDispatching);

I don't really like the empty while without any explanation, and I think the trailing ';' is easy to miss. I'd prefer to see a comment that explains what's going on, and hanging the ';' indented underneath - it should make it *harder* to make a mistake if anyone wants to extend the loop later. Alternatively, you could place the dispatch inside the loop itself, which would make the whole thing clearer, and avoid these problems altogether, though that wouldn't be consistent with what was there before. 

The other thing there is the removal of the spaces between the first mIsDispatching set, the while and the second mIsDispatching set, which makes it significantly less clear what's going on. Those should be added back in again. 

> @@ -1333,16 +1338,15 @@
> ...
>      /* Wait for the thread to return. */
> +    wInterlocked_set(0, &impl->mIsDispatching);

Similar style nitpicks - make sure the spacing is correct here.

I'll provide more feedback on the unit tests later.

Cheers, 

D

**Comment by MattMulhern** [comment]
Damian Maguire 2014-03-31 10:37:38 UTC
On the unit test front, the majority looks good to me. The main thing is to tidy up some of the formatting on the for loops. For example:

queuetest.cpp - line 403
> for (int x = 0; x!=m_numQueues; x++)

should be changed to:

> for (int x = 0; x != m_numQueues; x++)

The same goes throughout the rest of the files.

I do quite like the changes to tidy up the use of semaphores for signaling. Much cleaner than what was there before. 

Cheers, 

D

**Comment by MattMulhern** [comment]
Lee Skillen 2014-05-12 15:05:08 UTC
Hey Damian,

I completely agree with all of the above - Main point is the runtime error fixes so as long as they're still on track we're good.  Apologies about the obvious stylistic faults, some of them are copy-paste errors and some are fat finger errors - I'm completely on board with maintaining the status quo or adhering to the style guide!

Cheers,
Lee

**Comment by MattMulhern** [comment]
Damian Maguire 2014-05-20 09:28:11 UTC
Hey Lee, 

Just taking a look at raising the msgutils stuff as a separate ticket here, but had a quick question. You mention that the fixes you've added are to fix warnings, but I'm not sure where you're seeing those. Any chance you can point me to them (valgrind, static analysis, build etc)? Fix looks fine anyway, I just want to document the warnings that are being cleared by them.

Cheers, 

D

**Comment by MattMulhern** [comment]
Damian Maguire 2014-10-24 13:56:58 UTC
Hey Lee, 

Any chance you have a record of what warnings you were looking to fix here?

Cheers, 

D

**Comment by MattMulhern** [comment]
Lee Skillen 2014-10-24 14:13:36 UTC
Hey Damian,

Been a while. :-)

I had actually replied to these previously but it looks like the comment disappeared or never made it through (more likely), so apologies for that.

I think it was both static analysis (maybe-uninitialized) and valgrind runtime (actually uninitialized) - If the payload doesn't set the value via *result on the mamaMsg_getI32() call then it results in "val" having some random stack-based value.

I also think this was exhibited within avismsg because one of the following happened:

- CHECK_PAYLOAD() macro exited the function
- CHECK_NAME() macro exited the function
- avisMsg_getI32() exited early because the attribute wasn't in the message (most likely)

Lots of "think" and "maybe" there, but you can see the problem being a possibility by cold reading the code - Sorry!

Cheers,
Lee

**Comment by MattMulhern** [comment]
passes CI run with additional commit (was missing some changes from original submission).

**Comment by fquinner** [comment]
Needs a little more consideration before confirming this is the right approach... won't be included in 2.4.0 due to other priorities and related risk.

**Comment by fquinner** [comment]
Just manually merged this into next after resolving conflict: 2af17961756ce99a053bfbf0af2147d6a13729d6

**Pull request closed without merging**
