### PR TITLE
Bugfix mamdatetime 32 bit windows

### PR DESCRIPTION
**Pull request by garymolloy**
# Windows core on dateTime outside the range 1970-3000
## Summary
Windows doesn't support time_t values outside the range 1970, jan 1, 00:00:00 - 3000, dec 31, 23:59:59 for 64bit gmtime and 1970, jan 1, 00:00:00 - 2038, jan 18, 23:59:59 for 32bit gmtime. 

gmtime() is used by the OpenMAMA function utcTm() but due to it's date limitations (above) was the root cause of this issue.

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [x] Visual Studio
- [x] SCons
- [x] Unit Tests
- [ ] Examples

## Details
We have removed the compiler option '_USE_32BIT_TIME_T' when building 32bit and also replaced all calls to utcTm() with calls to Apache APR.  This included making changes to the following dateTime functions:
- mamaDateTime_getStructTmWithTz()
- mamaDateTime_getAsString()
- mamaDateTime_getTimeAsString()
- mamaDateTime_getDateAsString()
- mamaDateTime_getAsFormattedStringWithTz()
This will of course create a dependency on Apache APR now for building.

## Testing
10 new unittests have been added to cover dates outside the range of 1970 - 3000 (5 pre 1970 and 5 post 3000)

All unittests pass for 32bit builds

### CODE REVIEW

**Comment by dfedorov-solace** [comment]
This fixes issue #271, right?

**Comment by dfedorov-solace** [comment]
Frank, should we expect 6.2.1 release with this fix merged in?

**Comment by fquinner** [comment]
@dfedorov-solace yes when this is merged, a 6.2.1 RC will be next.

**Comment by fquinner** [comment]
Yeah it's a funny one this - apache apr seem to have a pretty weird build setup. It has definitions for cmake, but these only seem to work on windows. When it works though it works in a standard way with the headers going into `include/*`

It then uses automake on linux if you compile it or package managers. Builds of this actually nest the include directory into a configurable location but defaults to `include/apr-1`. The ubuntu folks (which the travis builds are based on) actually use `include/apr-1.0` just to be awkward. Luckily though they look like they provide a tool `apr-1-config` which allows you to resolve include paths after installation. That should be used in the build scripts on linux to resolve include paths.

The code should then use the header file names excluding the include subdirectory.

**Comment by fquinner** [comment]
Getting CI env ready for the new dependency here.

**Comment by fquinner** [comment]
OK linux and windows look ready to receive and build instructions updated - going to squash and merge this.

**Pull request merged**
