### PR TITLE
MAMA: Java unit tests: enhance with bridge/transport on cmd line

### PR DESCRIPTION
**Pull request by reed-jpm-alpert**
Add the bridge and transport to the cmd line for the Mama Java unit tests. Also add the MamaPublisher test that is referenced in the Main.java but not in git.

Signed-off-by: Reed Alpert <reed.alpert@gmail.com>

[Review on Reviewable](https://reviewable.io/reviews/openmama/openmama/88)

### CODE REVIEW

**Comment by MattMulhern** [comment]
Hi,
Patches look good, but one thing I want to check is around testing.
How have you been testing these changes? Can you provide some test output for us?

**Comment by reed-jpm-alpert** [comment]
This is test output from the publisher test by itself. Some of the others do not run on Solace bridge. The Java tests need some more overall work to make them OK with wmw, solace, and tick42rmds bridges (some symbol names for permissions). And to add the missing methods. This is really interim patches to get the MamaQueueGroup tested for that patch.

.2015-11-23 16:04:39:324: Normal SOLACE-PL-Bridge: (mama/c_cpp/src/c/payload/solacemsg/solacepayload.c:94): Solace Payload Bridge Created. Version: 7.1.1.17
2015-11-23 16:04:39:324: mama_loadPayloadBridge(): Sucessfully loaded solacemsg payload bridge from library [mamasolacemsgimpl]
2015-11-23 16:04:39:325: mama_loadPlugin(): Could not open plugin library [PublisherFieldCheck] [/home/tradtech/u045594/openmama_install/openmama_install_2.3.3_64_rh6/lib/libmamapluginPublisherFieldCheck.so: undefined symbol: mamaPublisherImpl_getTransportImpl]
2015-11-23 16:04:39:325:
********************************************************************************
Note: This build of the MAMA API is not enforcing entitlement checks.
Please see the Licensing file for details
**********************************************************************************
2015-11-23 16:04:39:326: Normal SOLACE-PL-Bridge: (mama/c_cpp/src/c/payload/solacemsg/solacepayload.c:94): Solace Payload Bridge Created. Version: 7.1.1.17
2015-11-23 16:04:39:326: mama_loadPayloadBridge(): Payload bridge solacemsg already loaded
2015-11-23 16:04:39:336: Normal SOLACE-MW-Bridge: (mama/c_cpp/src/c/bridge/solace/transport.c:526): Use of SolCache is enabled.
2015-11-23 16:04:39:336: idp-ttdnj02: Using default preinitial strategy: ON_GAP
2015-11-23 16:04:39:336: idp-ttdnj02: Using default dq strategy: DQ_SCHEME_DELIVER_ALL
2015-11-23 16:04:39:336: idp-ttdnj02: Using default ft strategy: DQ_FT_DO_NOT_WAIT_FOR_RECAP
2015-11-23 16:04:39:336: idp-ttdnj02: Pre-Recap cache disabled
2015-11-23 16:05:08:350: Normal SOLACE-MW-Bridge: (mama/c_cpp/src/c/bridge/solace/transport.c:803): Destroyed solClient session in transport name=idp-ttdnj02
.2015-11-23 16:05:08:351: mama_loadBridge(): Sucessfully loaded solace bridge from library [mamasolaceimpl]
2015-11-23 16:05:08:351: Using path specified in WOMBAT_PATH
2015-11-23 16:05:08:351: Using default properties file mama.properties
2015-11-23 16:05:08:351: Attempting to load MAMA properties from .
2015-11-23 16:05:08:352: Using path specified in WOMBAT_PATH
2015-11-23 16:05:08:352: Using default properties file mama.properties
2015-11-23 16:05:08:352: Attempting to load MAMA properties from .
2015-11-23 16:05:08:352: Normal SOLACE-PL-Bridge: (mama/c_cpp/src/c/payload/solacemsg/solacepayload.c:94): Solace Payload Bridge Created. Version: 7.1.1.17
2015-11-23 16:05:08:352: mama_loadPayloadBridge(): Sucessfully loaded solacemsg payload bridge from library [mamasolacemsgimpl]
2015-11-23 16:05:08:354: mama_loadPlugin(): Could not open plugin library [PublisherFieldCheck] [/home/tradtech/u045594/openmama_install/openmama_install_2.3.3_64_rh6/lib/libmamapluginPublisherFieldCheck.so: undefined symbol: mamaPublisherImpl_getTransportImpl]
2015-11-23 16:05:08:354:
********************************************************************************
Note: This build of the MAMA API is not enforcing entitlement checks.
Please see the Licensing file for details
**********************************************************************************
2015-11-23 16:05:08:354: Normal SOLACE-PL-Bridge: (mama/c_cpp/src/c/payload/solacemsg/solacepayload.c:94): Solace Payload Bridge Created. Version: 7.1.1.17
2015-11-23 16:05:08:354: mama_loadPayloadBridge(): Payload bridge solacemsg already loaded
2015-11-23 16:05:08:362: Normal SOLACE-MW-Bridge: (mama/c_cpp/src/c/bridge/solace/transport.c:526): Use of SolCache is enabled.
2015-11-23 16:05:08:362: idp-ttdnj02: Using default preinitial strategy: ON_GAP
2015-11-23 16:05:08:362: idp-ttdnj02: Using default dq strategy: DQ_SCHEME_DELIVER_ALL
2015-11-23 16:05:08:362: idp-ttdnj02: Using default ft strategy: DQ_FT_DO_NOT_WAIT_FOR_RECAP
2015-11-23 16:05:08:362: idp-ttdnj02: Pre-Recap cache disabled
2015-11-23 16:05:37:390: Normal SOLACE-MW-Bridge: (mama/c_cpp/src/c/bridge/solace/transport.c:803): Destroyed solClient session in transport name=idp-ttdnj02

Time: 58.074

OK (2 tests)

**Comment by MattMulhern** [comment]
Looks good, we'll get this into next soon.

**Comment by MattMulhern** [comment]
pushed to next branch (6064488b8253a3c9ffd395638d3203a3142e5596..b717ee1024f4dec4d40d7bb00ad0a0d4b365c086)

**Pull request closed without merging**
