### PR TITLE
fix build problem on mac

### PR DESCRIPTION
**Pull request by bill-torpey**
Looks like librt doesn't exist on mac.  

BTW, there doesn't appear to be any documentation on building on Mac.  I'm happy to help out here, although I think you mentioned that there is some work ongoing to refresh the website.

In any case, this is what I needed to do:

First, install dependencies:

```
brew install apr apr-util
brew install ossp-uuid
brew install qpid-proton
```

Then invoke build like so:

```
cmake -DAPR_ROOT=/usr/local/Cellar/apr/1.7.0/libexec/ ../src
```

### CODE REVIEW

**Comment by fquinner** [comment]
Yeah good catch I expect we simply didn't build the test tools on mac when porting to cmake. Can you target the `next` branch please?

**Comment by fquinner** [comment]
Conflicts here after branch switch can you update please?

**Comment by bill-torpey** [comment]
No idea what to do with this.  When I try to fix PR I still get all sorts of irrelevant stuff.

Please delete whatever you need to on your end and I'll recreate PR from scratch against next.  

I'll be sure to remember from now on not to target master, but use next instead.

**Comment by bill-torpey** [comment]
opened https://github.com/OpenMAMA/OpenMAMA/pull/406

**Pull request closed without merging**
